import assert from "node:assert/strict";
import { EventEmitter, once } from "node:events";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import { HostFunctionRegistry } from "../../packages/core/src/host-function-registry.js";
import { ControlPlaneService } from "../src/control-plane-service.js";
import { createControlPlaneServer } from "../src/http/server.js";
import { CodexCliRuntimeAdapter } from "../src/runtime-adapters/codex-cli-runtime-adapter.js";
import { RuntimeRegistry } from "../src/runtime-registry.js";
import { FileRunStore } from "../src/storage/file-run-store.js";

const DEFAULT_TARGET_SYMBOL = "semantix.host.apply_admitted_semantic";

function createSimpleSemanticProposal({
  workspaceRoot = process.cwd(),
  runId,
  nodeId = "node.codex.execute",
} = {}) {
  return {
    workspace_path: join(workspaceRoot, `${runId}-${nodeId}.txt`),
    summary: "Codex produced a strict semantic proposal.",
  };
}

function createCodeChangeProposal({
  workspaceRoot = process.cwd(),
  runId,
  nodeId = "node.codex.execute",
} = {}) {
  const relativeTargetPath = `src/generated/${runId}-${nodeId}.txt`;
  return {
    workspace_path: join(workspaceRoot, relativeTargetPath),
    summary: "Codex produced a strict semantic proposal.",
    diff_preview: `diff --git a/${relativeTargetPath} b/${relativeTargetPath}\n@@ -0,0 +1 @@\n+// generated by ${nodeId}\n`,
    references: [
      {
        kind: "function",
        name: "verifyToken",
        path: "src/auth/verifyToken.js",
        source: "grounded",
        required: true,
        supporting_context: ["src/auth/verifyToken.js"],
      },
    ],
    parameters: [],
    supporting_context: [
      {
        kind: "file",
        value: "src/auth/verifyToken.js",
        path: "src/auth/verifyToken.js",
      },
      {
        kind: "symbol",
        value: "verifyToken",
        path: "src/auth/verifyToken.js",
      },
    ],
  };
}

function nodeRequiresCodeChangeProposal(node) {
  return Boolean(node?.baseValidationSchema?.properties?.changes || node?.baseValidationSchema?.properties?.diff_preview);
}

function createRunnerResult(runId, nodeId = "node.codex.execute") {
  return {
    exitCode: 0,
    stdout: JSON.stringify(createSimpleSemanticProposal({ runId, nodeId })),
    stderr: "",
  };
}

function createBlueprint({
  allowedRoot,
  forbiddenRoots = ["/root"],
  targetSymbol = DEFAULT_TARGET_SYMBOL,
} = {}) {
  return {
    intent_contract: {
      primary_directive: "Implement the Semantix v0.5 governed code-change demo.",
      strict_boundaries: ["Keep deterministic execution host-authoritative."],
      success_state: "A deterministic host function receives only admitted semantic output.",
    },
    semantic_frames: [
      {
        frame_id: "frame.semantic.generate",
        node_id: "node.semantic.generate",
        prompt: "Compile a strict JSON proposal for deterministic execution.",
        context: {
          phase: "v0.5",
        },
        hard_constraints: [
          {
            kind: "path_policy",
            field: "workspace_path",
            required: true,
            allowed_roots: [allowedRoot],
            forbidden_roots: forbiddenRoots,
          },
        ],
      },
    ],
    execution_graph: {
      nodes: [
        {
          node_id: "node.semantic.generate",
          kind: "semantic_generation",
          title: "Compile Semantic Output",
          depends_on: [],
          frame_id: "frame.semantic.generate",
          base_validation_schema: {
            type: "object",
            additionalProperties: false,
            required: ["workspace_path", "summary"],
            properties: {
              workspace_path: {
                type: "string",
              },
              summary: {
                type: "string",
              },
            },
          },
        },
        {
          node_id: "node.approval.execute",
          kind: "approval_gate",
          title: "Approve Deterministic Dispatch",
          depends_on: ["node.semantic.generate"],
          target_node_id: "node.execute.host",
          reason: "Fresh approval is required after semantic admission.",
        },
        {
          node_id: "node.execute.host",
          kind: "deterministic_execution",
          title: "Dispatch Host Function",
          depends_on: ["node.semantic.generate", "node.approval.execute"],
          input_node_id: "node.semantic.generate",
          target_symbol: targetSymbol,
          state_effect_preview: {
            id: "effect.preview.host",
            kind: "file",
            operation: "modify",
            target: targetSymbol,
            summary: `Preview for ${targetSymbol}.`,
            previewRef: "preview://host/1",
            policyState: "review_required",
            riskFlags: ["advisory_preview"],
            reversibility: {
              status: "reversible",
              mechanism: "host_defined",
            },
            enforcement: {
              owner: "policy",
              status: "review_required",
              details: "Advisory only in v0.5.",
            },
          },
        },
      ],
    },
  };
}

function createFreshnessEnvelope(artifact, node, gate) {
  return {
    planVersion: artifact.planVersion,
    graphVersion: artifact.graphVersion,
    artifactHash: artifact.artifactHash,
    nodeId: node.id,
    nodeRevision: node.revision,
    gateId: gate?.id,
  };
}

class FakeSessionConnector {
  constructor() {
    this.notifications = new EventEmitter();
    this.threadCounter = 0;
    this.turnCounter = 0;
    this.threads = new Map();
  }

  onNotification(listener) {
    this.notifications.on("notification", listener);
    return () => {
      this.notifications.off("notification", listener);
    };
  }

  emit(method, params) {
    this.notifications.emit("notification", { method, params });
  }

  async healthCheck() {
    return {
      healthy: true,
      transport: "fake-app-server",
    };
  }

  async startThread(params = {}) {
    this.threadCounter += 1;
    const threadId = `runtime-thread-${this.threadCounter}`;
    const thread = {
      id: threadId,
      preview: "",
      status: { type: "idle" },
      cwd: params.cwd ?? "/workspace/project",
      turns: [],
    };
    this.threads.set(threadId, thread);
    queueMicrotask(() => {
      this.emit("thread/started", { thread });
    });

    return {
      thread,
      runtimeSessionId: threadId,
      model: "gpt-5.3-codex",
      modelProvider: "openai",
      cwd: thread.cwd,
      approvalPolicy: params.approvalPolicy ?? "never",
      sandbox: { type: "workspaceWrite" },
      reasoningEffort: null,
    };
  }

  async startTurn({ threadId, input }) {
    const thread = this.threads.get(threadId);
    this.turnCounter += 1;
    const turn = {
      id: `runtime-turn-${this.turnCounter}`,
      items: [],
      status: "inProgress",
      startedAt: Date.now(),
      completedAt: null,
      durationMs: null,
    };
    thread.status = { type: "active", activeFlags: [] };
    thread.preview = input.find((item) => item.type === "text")?.text ?? thread.preview;
    thread.turns.push({
      ...turn,
      items: input.map((item, index) => ({
        type: "userMessage",
        id: `item-${this.turnCounter}-${index + 1}`,
        content:
          item.type === "text"
            ? [{ type: "text", text: item.text, text_elements: [] }]
            : [],
      })),
    });

    queueMicrotask(() => {
      this.emit("thread/status/changed", {
        threadId,
        status: thread.status,
      });
      this.emit("turn/started", {
        threadId,
        turn,
      });
    });

    return {
      runtimeTurnId: turn.id,
      turn,
    };
  }

  completeTurn(threadId, turnId, status = "completed") {
    const thread = this.threads.get(threadId);
    const turn = thread?.turns.find((candidate) => candidate.id === turnId);
    if (!thread || !turn) {
      return;
    }

    turn.status = status;
    turn.completedAt = Date.now();
    turn.durationMs = Math.max(1, turn.completedAt - turn.startedAt);
    thread.status = { type: "idle" };
    this.emit("thread/status/changed", {
      threadId,
      status: thread.status,
    });
    this.emit("turn/completed", {
      threadId,
      turn,
    });
  }

  async readThread({ threadId }) {
    const thread = this.threads.get(threadId);
    return {
      ...thread,
      turns: [...thread.turns],
    };
  }

  async listTurns({ threadId }) {
    return [...(this.threads.get(threadId)?.turns ?? [])];
  }

  async interruptTurn({ threadId, turnId }) {
    this.completeTurn(threadId, turnId, "interrupted");
    return {};
  }
}

async function createHarness(t, options = {}) {
  const rootDir = await mkdtemp(join(tmpdir(), "semantix-control-plane-server-"));
  const workspaceRoot = join(rootDir, "workspace");
  await mkdir(workspaceRoot, { recursive: true });
  await mkdir(join(workspaceRoot, "src", "auth"), { recursive: true });
  await writeFile(
    join(workspaceRoot, "src", "auth", "verifyToken.js"),
    "export function verifyToken(token) {\n  return Boolean(token);\n}\n",
  );
  const store = new FileRunStore({
    rootDir,
  });
  const registry = new RuntimeRegistry();
  const sessionConnector = new FakeSessionConnector();
  const hostInvocations = [];
  const hostFunctionRegistry =
    options.hostFunctionRegistry ??
    new HostFunctionRegistry([
      {
        targetSymbol: DEFAULT_TARGET_SYMBOL,
        async preview(input) {
          return {
            id: "effect.preview.host",
            kind: "file",
            operation: "modify",
            target: input.workspace_path,
            summary: `Would modify ${input.workspace_path}.`,
            previewRef: "preview://host/1",
            diff: `diff --git a/${input.workspace_path} b/${input.workspace_path}\n@@ -1 +1 @@\n-old\n+new\n`,
            diffPreview: "@@ -1 +1 @@\n-old\n+new\n",
            policyState: "review_required",
            riskFlags: ["advisory_preview"],
            reversibility: {
              status: "reversible",
              mechanism: "local_vcs",
            },
            enforcement: {
              owner: "policy",
              status: "review_required",
              details: "Advisory only in v0.5.",
            },
          };
        },
        async invoke(input) {
          hostInvocations.push(input);
          return {
            outputSummary: `Applied ${input.summary}.`,
          };
        },
      },
    ]);
  registry.registerRuntimeAdapter(
    new CodexCliRuntimeAdapter({
      sessionConnector,
      runner:
        options.runner ??
        (async ({ runId, node }) => ({
          exitCode: 0,
          stdout: JSON.stringify(
            nodeRequiresCodeChangeProposal(node)
              ? createCodeChangeProposal({
                  workspaceRoot,
                  runId,
                  nodeId: node?.id,
                })
              : createSimpleSemanticProposal({
                  workspaceRoot,
                  runId,
                  nodeId: node?.id,
                }),
          ),
          stderr: "",
        })),
    }),
  );

  const service = new ControlPlaneService({
    store,
    runtimeRegistry: registry,
    hostFunctionRegistry,
  });

  t.after(async () => {
    await service.close();
    await rm(rootDir, { recursive: true, force: true });
  });

  return {
    service,
    sessionConnector,
    workspaceRoot,
    hostInvocations,
  };
}

async function compileRun(service, runId, workspaceRoot, overrides = {}) {
  return service.compilePlan({
    runId,
    actor: "test",
    cwd: workspaceRoot,
    blueprint:
      overrides.blueprint ??
      createBlueprint({
        allowedRoot: workspaceRoot,
        targetSymbol: overrides.targetSymbol,
        forbiddenRoots: overrides.forbiddenRoots,
      }),
  });
}

async function postJson(url, body) {
  const response = await fetch(url, {
    method: "POST",
    headers: {
      "content-type": "application/json",
    },
    body: JSON.stringify(body),
  });

  return response;
}

async function readEvent(streamReader) {
  while (true) {
    const frame = await streamReader.nextFrame();
    if (!frame) {
      throw new Error("Expected an SSE frame but the stream ended.");
    }

    if (frame.event === "ping") {
      continue;
    }

    return frame.data;
  }
}

async function readUntilType(streamReader, eventType) {
  while (true) {
    const event = await readEvent(streamReader);
    if (event.type === eventType) {
      return event;
    }
  }
}

async function openSse(url) {
  const controller = new AbortController();
  const response = await fetch(url, {
    headers: {
      accept: "text/event-stream",
    },
    signal: controller.signal,
  });

  assert.equal(response.status, 200);

  const decoder = new TextDecoder();
  const reader = response.body.getReader();
  let buffer = "";

  return {
    async nextFrame() {
      while (true) {
        const splitIndex = buffer.indexOf("\n\n");
        if (splitIndex >= 0) {
          const rawFrame = buffer.slice(0, splitIndex);
          buffer = buffer.slice(splitIndex + 2);
          if (!rawFrame.trim()) {
            continue;
          }

          const frame = {
            event: "message",
            data: undefined,
          };

          for (const line of rawFrame.split("\n")) {
            if (line.startsWith("event:")) {
              frame.event = line.slice(6).trim();
            }
            if (line.startsWith("data:")) {
              frame.data = JSON.parse(line.slice(5).trimStart());
            }
          }

          return frame;
        }

        const { done, value } = await reader.read();
        if (done) {
          return null;
        }
        buffer += decoder.decode(value, { stream: true });
      }
    },
    close() {
      controller.abort();
    },
  };
}

test("streams the same normalized events to multiple SSE clients", async (t) => {
  const { service, workspaceRoot } = await createHarness(t);
  const server = createControlPlaneServer({
    service,
  });
  let browserClient = null;
  let stxClient = null;

  t.after(async () => {
    browserClient?.close();
    stxClient?.close();
    server.close();
    await once(server, "close");
  });

  server.listen(0, "127.0.0.1");
  await once(server, "listening");

  const { port } = server.address();
  const baseUrl = `http://127.0.0.1:${port}`;

  await service.createOrUpdateIntent({
    runId: "run-sse",
    primaryDirective: "Implement event streaming.",
    strictBoundaries: ["Keep the backend authoritative."],
    successState: "Both clients receive normalized updates.",
    actor: "test",
  });

  browserClient = await openSse(`${baseUrl}/runs/run-sse/events`);
  stxClient = await openSse(`${baseUrl}/runs/run-sse/events`);

  const artifact = await compileRun(service, "run-sse", workspaceRoot);

  const pausedArtifact = await service.executeApprovedNodes({
    runId: "run-sse",
    actor: "operator",
  });
  const executableNode = pausedArtifact.plan.nodes.find(
    (node) => node.nodeType === "deterministic_execution",
  );
  const approvalGate = pausedArtifact.plan.approvalGates.find((gate) => gate.required);

  const artifactEventA = await readUntilType(browserClient, "artifact.generated");
  const artifactEventB = await readUntilType(stxClient, "artifact.generated");

  assert.equal(artifactEventA.runId, "run-sse");
  assert.equal(artifactEventB.runId, "run-sse");
  assert.equal(artifactEventA.artifactHash, artifact.artifactHash);
  assert.equal(artifactEventB.artifactHash, artifact.artifactHash);

  await service.submitApprovalAction({
    runId: "run-sse",
    actor: "reviewer",
    action: "approve",
    planVersion: pausedArtifact.planVersion,
    graphVersion: pausedArtifact.graphVersion,
    artifactHash: pausedArtifact.artifactHash,
    nodeId: executableNode.id,
    nodeRevision: executableNode.revision,
    gateId: approvalGate.id,
  });

  const approvalEventA = await readUntilType(browserClient, "approval.accepted");
  const approvalEventB = await readUntilType(stxClient, "approval.accepted");

  assert.equal(approvalEventA.runId, "run-sse");
  assert.equal(approvalEventB.runId, "run-sse");
  assert.equal(approvalEventA.nodeId, executableNode.id);
  assert.equal(approvalEventB.nodeId, executableNode.id);
});

test("bootstraps a run and lists run summaries over HTTP", async (t) => {
  const { service, workspaceRoot } = await createHarness(t);
  const server = createControlPlaneServer({
    service,
  });

  t.after(async () => {
    server.close();
    await once(server, "close");
  });

  server.listen(0, "127.0.0.1");
  await once(server, "listening");

  const { port } = server.address();
  const baseUrl = `http://127.0.0.1:${port}`;

  const bootstrapResponse = await fetch(`${baseUrl}/runs`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
    },
    body: JSON.stringify({
      autoExecuteSemanticAdmission: false,
      cwd: workspaceRoot,
      primaryDirective: "Leave browser fixtures and use the real Semantix backend.",
      strictBoundaries: ["Preserve the Semantix DTO vocabulary."],
      successState: "The browser receives a live review artifact.",
      actor: "browser",
    }),
  });

  assert.equal(bootstrapResponse.status, 200);
  const artifact = await bootstrapResponse.json();
  assert.match(artifact.runId, /^run-/);
  assert.equal(artifact.planVersion, 1);

  const listResponse = await fetch(`${baseUrl}/runs`);
  assert.equal(listResponse.status, 200);

  const runs = await listResponse.json();
  assert.equal(runs.length, 1);
  assert.equal(runs[0].runId, artifact.runId);
  assert.equal(runs[0].artifact.artifactHash, artifact.artifactHash);
  assert.equal(runs[0].summary.planStatus, artifact.plan.status);
  assert.equal(
    runs[0].intent.primaryDirective,
    "Leave browser fixtures and use the real Semantix backend.",
  );
});

test("resolves preview content JSON by previewRef over HTTP", async (t) => {
  const { service } = await createHarness(t);
  const server = createControlPlaneServer({
    service,
  });

  t.after(async () => {
    server.close();
    await once(server, "close");
  });

  server.listen(0, "127.0.0.1");
  await once(server, "listening");

  const { port } = server.address();
  const baseUrl = `http://127.0.0.1:${port}`;

  await service.createOrUpdateIntent({
    runId: "run-preview-http",
    primaryDirective: "Modify the control surface host so the browser UI is bundled.",
    strictBoundaries: ["Preserve the Semantix DTO vocabulary."],
    successState: "The browser and stx resolve the same previewRef through one backend path.",
    actor: "test",
  });

  const artifact = await service.compilePlan({
    runId: "run-preview-http",
    actor: "test",
  });

  const effect = artifact.plan.stateEffects.find((entry) => entry.previewRef);
  assert.ok(effect);
  assert.ok(effect.previewRef);
  assert.equal(effect.preview, undefined);
  assert.equal(effect.diff, undefined);

  const previewResponse = await fetch(
    `${baseUrl}/runs/run-preview-http/previews?previewRef=${encodeURIComponent(effect.previewRef)}`,
  );

  assert.equal(previewResponse.status, 200);
  const preview = await previewResponse.json();
  assert.equal(preview.previewRef, effect.previewRef);
  assert.equal(preview.runId, "run-preview-http");
  assert.equal(preview.planVersion, artifact.planVersion);
  assert.equal(preview.graphVersion, artifact.graphVersion);
  assert.equal(preview.artifactHash, artifact.artifactHash);
  assert.equal(preview.mediaType, "text/plain; charset=utf-8");
  assert.ok(preview.content.includes(`! previewRef ${effect.previewRef}`));
  assert.ok(preview.content.includes(effect.summary));
});

test("executes the Semantix v0.5 happy path over HTTP with stable proposed changes and diff metadata", async (t) => {
  const { service, workspaceRoot, hostInvocations } = await createHarness(t);
  await compileRun(service, "run-http-v05-happy", workspaceRoot);

  const server = createControlPlaneServer({
    service,
  });

  t.after(async () => {
    server.close();
    await once(server, "close");
  });

  server.listen(0, "127.0.0.1");
  await once(server, "listening");

  const { port } = server.address();
  const baseUrl = `http://127.0.0.1:${port}`;

  const executeResponse = await postJson(`${baseUrl}/runs/run-http-v05-happy/execute`, {
    actor: "operator",
  });
  assert.equal(executeResponse.status, 200);
  const pausedArtifact = await executeResponse.json();
  const semanticNode = pausedArtifact.plan.nodes.find((node) => node.id === "node.semantic.generate");
  const deterministicNode = pausedArtifact.plan.nodes.find((node) => node.id === "node.execute.host");
  const approvalGate = pausedArtifact.plan.approvalGates.find((gate) => gate.targetNodeId === deterministicNode.id);
  const pausedEffect = pausedArtifact.plan.stateEffects.find(
    (entry) => entry.target === semanticNode.admittedOutput.workspace_path,
  );

  assert.equal(pausedArtifact.plan.status, "paused");
  assert.ok(pausedEffect);
  assert.equal(pausedEffect.diffPreview, "@@ -1 +1 @@\n-old\n+new\n");

  const inspectorResponse = await fetch(
    `${baseUrl}/runs/run-http-v05-happy/nodes/${encodeURIComponent(deterministicNode.id)}/inspector`,
  );
  assert.equal(inspectorResponse.status, 200);
  const inspector = await inspectorResponse.json();
  const inspectorEffect = inspector.outputPreview.stateEffects.find(
    (entry) => entry.target === semanticNode.admittedOutput.workspace_path,
  );
  assert.ok(inspectorEffect);
  assert.equal(inspectorEffect.previewRef, "preview://host/1");
  assert.notEqual(inspectorEffect.target, DEFAULT_TARGET_SYMBOL);
  assert.equal(inspector.outputPreview.diffPreview, "@@ -1 +1 @@\n-old\n+new\n");
  assert.equal(inspectorEffect.previewRef, "preview://host/1");

  const approvalResponse = await postJson(`${baseUrl}/runs/run-http-v05-happy/approvals`, {
    actor: "reviewer",
    action: "approve",
    ...createFreshnessEnvelope(pausedArtifact, deterministicNode, approvalGate),
  });
  assert.equal(approvalResponse.status, 200);

  const resumeResponse = await postJson(`${baseUrl}/runs/run-http-v05-happy/resume`, {
    actor: "operator",
    checkpointId: pausedArtifact.plan.checkpoints.at(-1).id,
    ...createFreshnessEnvelope(pausedArtifact, deterministicNode, approvalGate),
  });
  assert.equal(resumeResponse.status, 200);
  const completedArtifact = await resumeResponse.json();

  assert.equal(completedArtifact.plan.status, "completed");
  assert.equal(hostInvocations.length, 1);
  assert.deepEqual(hostInvocations[0], semanticNode.admittedOutput);

  const artifactResponse = await fetch(`${baseUrl}/runs/run-http-v05-happy/artifact`);
  assert.equal(artifactResponse.status, 200);
  const storedArtifact = await artifactResponse.json();
  const storedEffect = storedArtifact.plan.stateEffects.find(
    (entry) => entry.target === semanticNode.admittedOutput.workspace_path,
  );
  assert.ok(storedEffect);
  assert.equal(storedEffect.diffPreview, "@@ -1 +1 @@\n-old\n+new\n");
});

test("Semantix blocks a plausible bad change over HTTP before deterministic execution", async (t) => {
  const issue = {
    code: "unsafe-target",
    summary: "The diff would rewrite a secrets file outside the approved scope.",
    blocking: true,
    evidence: [
      {
        kind: "target_path",
        detail: "workspace_path resolved to workspace/secrets.env",
      },
    ],
    interventions: [
      {
        kind: "retarget",
        detail: "Restrict the change to src/app/config.json.",
      },
    ],
  };
  const topLevelEvidence = [
    {
      kind: "diff_hunk",
      detail: "@@ -1 +1 @@",
    },
  ];
  const topLevelInterventions = [
    {
      kind: "manual_review",
      detail: "Pause and require reviewer intervention.",
    },
  ];
  const hostInvocations = [];
  const { service, workspaceRoot } = await createHarness(t, {
    hostFunctionRegistry: new HostFunctionRegistry([
      {
        targetSymbol: DEFAULT_TARGET_SYMBOL,
        async preview(input) {
          return {
            id: "effect.preview.host",
            kind: "file",
            operation: "modify",
            target: input.workspace_path,
            summary: `Would modify ${input.workspace_path}.`,
            previewRef: "preview://host/1",
            diff: `diff --git a/${input.workspace_path} b/${input.workspace_path}\n@@ -1 +1 @@\n-SECRET=prod\n+SECRET=test\n`,
            diffPreview: "@@ -1 +1 @@\n-SECRET=prod\n+SECRET=test\n",
            policyState: "block",
            riskFlags: ["unsafe_code_change"],
            issues: [issue],
            evidence: topLevelEvidence,
            interventions: topLevelInterventions,
            reversibility: {
              status: "reversible",
              mechanism: "local_vcs",
            },
            enforcement: {
              owner: "policy",
              status: "block",
              details: issue.summary,
            },
          };
        },
        async invoke(input) {
          hostInvocations.push(input);
          return {
            outputSummary: `Applied ${input.summary}.`,
          };
        },
      },
    ]),
  });
  await compileRun(service, "run-http-v05-blocked", workspaceRoot);

  const server = createControlPlaneServer({
    service,
  });

  t.after(async () => {
    server.close();
    await once(server, "close");
  });

  server.listen(0, "127.0.0.1");
  await once(server, "listening");

  const { port } = server.address();
  const baseUrl = `http://127.0.0.1:${port}`;

  const executeResponse = await postJson(`${baseUrl}/runs/run-http-v05-blocked/execute`, {
    actor: "operator",
  });
  assert.equal(executeResponse.status, 200);
  const pausedArtifact = await executeResponse.json();
  const deterministicNode = pausedArtifact.plan.nodes.find((node) => node.id === "node.execute.host");
  const approvalGate = pausedArtifact.plan.approvalGates.find((gate) => gate.targetNodeId === deterministicNode.id);

  const artifactResponse = await fetch(`${baseUrl}/runs/run-http-v05-blocked/artifact`);
  assert.equal(artifactResponse.status, 200);
  const artifact = await artifactResponse.json();
  const blockedEffect = artifact.plan.stateEffects.find((entry) => entry.issues?.length);
  assert.ok(blockedEffect);
  assert.deepEqual(blockedEffect.issues, [issue]);
  assert.deepEqual(blockedEffect.evidence, topLevelEvidence);
  assert.deepEqual(blockedEffect.interventions, topLevelInterventions);

  const inspectorResponse = await fetch(
    `${baseUrl}/runs/run-http-v05-blocked/nodes/${encodeURIComponent(deterministicNode.id)}/inspector`,
  );
  assert.equal(inspectorResponse.status, 200);
  const inspector = await inspectorResponse.json();
  const inspectorEffect = inspector.outputPreview.stateEffects.find(
    (entry) => entry.target === blockedEffect.target,
  );
  assert.ok(inspectorEffect);
  assert.notEqual(inspectorEffect.target, DEFAULT_TARGET_SYMBOL);
  assert.deepEqual(inspector.issues, [issue]);
  assert.deepEqual(inspector.evidence, [...topLevelEvidence, ...issue.evidence]);
  assert.deepEqual(inspector.interventions, [...topLevelInterventions, ...issue.interventions]);
  assert.equal(inspector.critique.blocking, true);
  assert.equal(inspector.outputPreview.diffPreview, "@@ -1 +1 @@\n-SECRET=prod\n+SECRET=test\n");

  const approvalResponse = await postJson(`${baseUrl}/runs/run-http-v05-blocked/approvals`, {
    actor: "reviewer",
    action: "approve",
    ...createFreshnessEnvelope(pausedArtifact, deterministicNode, approvalGate),
  });
  assert.equal(approvalResponse.status, 400);
  const approvalError = await approvalResponse.json();
  assert.equal(approvalError.error, "VALIDATION_ERROR");
  assert.equal(approvalError.details.blockingReason, issue.summary);
  assert.equal(approvalError.details.issues[0].code, "unsafe-target");
  assert.equal(hostInvocations.length, 0);
});

test("creates sessions, submits turns, and replays session-filtered events over HTTP", async (t) => {
  const { service, sessionConnector } = await createHarness(t);
  const server = createControlPlaneServer({
    service,
  });
  let replayClient = null;

  t.after(async () => {
    replayClient?.close();
    server.close();
    await once(server, "close");
  });

  server.listen(0, "127.0.0.1");
  await once(server, "listening");

  const { port } = server.address();
  const baseUrl = `http://127.0.0.1:${port}`;

  await service.createOrUpdateIntent({
    runId: "run-session-http",
    primaryDirective: "Support multi-turn Codex sessions through the control plane.",
    strictBoundaries: ["Keep browser and stx on one backend contract."],
    successState: "Sessions are backend-managed and stream normalized events.",
    actor: "test",
  });

  const artifact = await service.compilePlan({
    runId: "run-session-http",
    actor: "test",
  });
  const executableNode = artifact.plan.nodes.find((node) => node.nodeType === "semantic_generation");

  const createResponse = await fetch(`${baseUrl}/runs/run-session-http/sessions`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
    },
    body: JSON.stringify({
      actor: "operator",
      planVersion: artifact.planVersion,
      graphVersion: artifact.graphVersion,
      artifactHash: artifact.artifactHash,
      nodeId: executableNode.id,
      nodeRevision: executableNode.revision,
    }),
  });
  assert.equal(createResponse.status, 200);
  const session = await createResponse.json();

  const turnResponse = await fetch(
    `${baseUrl}/runs/run-session-http/sessions/${session.sessionId}/turns`,
    {
      method: "POST",
      headers: {
        "content-type": "application/json",
      },
      body: JSON.stringify({
        actor: "operator",
        clientTurnId: "session-http-turn",
        input: "Send the next bounded runtime turn.",
        planVersion: artifact.planVersion,
        graphVersion: artifact.graphVersion,
        artifactHash: artifact.artifactHash,
        nodeId: executableNode.id,
        nodeRevision: executableNode.revision,
      }),
    },
  );
  assert.equal(turnResponse.status, 200);
  const startedTurn = await turnResponse.json();
  sessionConnector.completeTurn(session.runtimeSessionId, startedTurn.turn.runtimeTurnId);
  let sessionDetail;
  for (let attempt = 0; attempt < 10; attempt += 1) {
    const sessionDetailResponse = await fetch(
      `${baseUrl}/runs/run-session-http/sessions/${session.sessionId}?includeTurns=1`,
    );
    assert.equal(sessionDetailResponse.status, 200);
    sessionDetail = await sessionDetailResponse.json();
    if (sessionDetail.turns[0]?.status === "completed") {
      break;
    }
    await new Promise((resolve) => setTimeout(resolve, 20));
  }
  assert.equal(sessionDetail.turns.length, 1);
  assert.equal(sessionDetail.turns[0].status, "completed");

  replayClient = await openSse(
    `${baseUrl}/runs/run-session-http/events?after=0&sessionId=${encodeURIComponent(session.sessionId)}`,
  );

  const replayedSessionCreated = await readUntilType(replayClient, "session.created");
  const replayedTurnAccepted = await readUntilType(replayClient, "turn.accepted");

  assert.equal(replayedSessionCreated.sessionId, session.sessionId);
  assert.equal(replayedTurnAccepted.sessionId, session.sessionId);
});

test("serves the bundled stx UI build and redirects legacy UI routes to /index.html", async (t) => {
  const { service } = await createHarness(t);
  const uiDir = await mkdtemp(join(tmpdir(), "semantix-control-plane-ui-"));

  await mkdir(join(uiDir, "assets"), { recursive: true });
  await mkdir(join(uiDir, "Design"), { recursive: true });
  await writeFile(join(uiDir, "index.html"), "<!doctype html><title>Bundled stx UI</title>");
  await writeFile(join(uiDir, "assets", "app.js"), "window.semantixUi = true;\n");
  await writeFile(join(uiDir, "Design", "Semantix.html"), "<!doctype html><title>Legacy root</title>");
  await writeFile(
    join(uiDir, "Design", "Semantix Chat.html"),
    "<!doctype html><title>Legacy chat</title>",
  );
  await writeFile(
    join(uiDir, "Design", "Semantix Canvas.html"),
    "<!doctype html><title>Legacy canvas</title>",
  );
  await writeFile(
    join(uiDir, "Design", "Semantix How It Works.html"),
    "<!doctype html><title>Legacy how it works</title>",
  );

  const server = createControlPlaneServer({
    service,
    uiDir,
  });

  t.after(async () => {
    server.close();
    await once(server, "close");
    await rm(uiDir, { recursive: true, force: true });
  });

  server.listen(0, "127.0.0.1");
  await once(server, "listening");

  const { port } = server.address();
  const baseUrl = `http://127.0.0.1:${port}`;

  const rootResponse = await fetch(`${baseUrl}/`, {
    redirect: "manual",
  });
  assert.equal(rootResponse.status, 302);
  assert.equal(rootResponse.headers.get("location"), "/index.html");

  const mainHtmlResponse = await fetch(`${baseUrl}/index.html`);
  assert.equal(mainHtmlResponse.status, 200);
  assert.match(mainHtmlResponse.headers.get("content-type"), /text\/html/);
  assert.match(await mainHtmlResponse.text(), /Bundled stx UI/);

  const bundleResponse = await fetch(`${baseUrl}/assets/app.js`);
  assert.equal(bundleResponse.status, 200);
  assert.match(bundleResponse.headers.get("content-type"), /application\/javascript/);
  assert.match(await bundleResponse.text(), /window\.semantixUi/);

  const legacyRoutes = [
    "/chat",
    "/canvas",
    "/how-it-works",
    "/Design/Semantix.html",
    "/Design/Semantix%20Chat.html",
    "/Design/Semantix%20Canvas.html",
    "/Design/Semantix%20How%20It%20Works.html",
  ];

  for (const route of legacyRoutes) {
    const legacyResponse = await fetch(`${baseUrl}${route}`, {
      redirect: "manual",
    });
    assert.equal(legacyResponse.status, 302);
    assert.equal(legacyResponse.headers.get("location"), "/index.html");
  }
});
